### ISSUE TITLE
not work client

### ISSUE THREAD

**Issue by ghost** [Bit-Wasp/stratum-php#1]
Hello. It is a good class for work with Electrum. 
But not all commands is work..

**Comment by afk11** [comment]
You're right - I have to revisit this. It doesn't support subscriptions, but that's because I was unfamiliar with react. 

Do you use react normally? You could write a new Client instance that instantly creates and maintains a Connection. The api-like class doesn't really do this, so you want to set up events against the connection to handle notifications like blockchain.headers.subscribe. 

I don't make much use of this class really, I'd welcome a pull-request with the feature if you have the time.

**Comment by rylskov** [comment]
I'm trying to understand. I am not familiar with React, too =)

**Comment by rylskov** [comment]
I made some changes into fork. I'm not sure that everything is correct, because I just started working with php-frameworks. But the basic code to receive notifications subscribe-methods I noted.
